#[path = "utils/file.rs"]
mod file;
mod day_1;
mod day_2;
mod day_3;
mod day_4;
mod day_5;
mod day_6;
mod day_7;
mod day_7_1;
mod day_8;
mod day_8_1;
mod day_9;
mod day_10;
mod day_11;
mod day_12;
mod day_13;
mod day_14;
mod day_15;

use crate::day_1::solve_the_puzzle_1_0;
use crate::day_1::solve_the_puzzle_1_1;
use crate::day_2::solve_the_puzzle_2_0;
use crate::day_2::solve_the_puzzle_2_1;
use crate::day_3::solve_the_puzzle_3_0;
use crate::day_3::solve_the_puzzle_3_1;
use crate::day_4::solve_the_puzzle_4_0;
use crate::day_4::solve_the_puzzle_4_1;
use crate::day_5::solve_the_puzzle_5_0;
use crate::day_5::solve_the_puzzle_5_1;
use crate::day_6::solve_the_puzzle_6_0;
use crate::day_6::solve_the_puzzle_6_1;
use crate::day_7::solve_the_puzzle_7_0;
use crate::day_7_1::solve_the_puzzle_7_1;
use crate::day_8::solve_the_puzzle_8_0;
use crate::day_8_1::solve_the_puzzle_8_1;
use crate::day_9::solve_the_puzzle_9_0;
use crate::day_9::solve_the_puzzle_9_1;
use crate::day_10::solve_the_puzzle_10_0;
use crate::day_10::solve_the_puzzle_10_1;
use crate::day_11::solve_the_puzzle_11_0;
use crate::day_11::solve_the_puzzle_11_1;
use crate::day_12::solve_the_puzzle_12_0;
use crate::day_12::solve_the_puzzle_12_1;
use crate::day_13::solve_the_puzzle_13_0;
use crate::day_13::solve_the_puzzle_13_1;
use crate::day_14::solve_the_puzzle_14_0;
use crate::day_14::solve_the_puzzle_14_1;
use crate::day_15::solve_the_puzzle_15_0;
use crate::day_15::solve_the_puzzle_15_1;

fn main() {
    solve_the_puzzle_1_0();
    solve_the_puzzle_1_1();
    solve_the_puzzle_2_0();
    solve_the_puzzle_2_1();
    solve_the_puzzle_3_0();
    solve_the_puzzle_3_1();
    solve_the_puzzle_4_0();
    solve_the_puzzle_4_1();
    solve_the_puzzle_5_0();
    solve_the_puzzle_5_1();
    solve_the_puzzle_6_0();
    //solve_the_puzzle_6_1();
    solve_the_puzzle_7_0();
    //solve_the_puzzle_7_1();
    solve_the_puzzle_8_0();
    solve_the_puzzle_8_1();
    solve_the_puzzle_9_0();
    //solve_the_puzzle_9_1();
    solve_the_puzzle_10_0();
    solve_the_puzzle_10_1();
    solve_the_puzzle_11_0();
    solve_the_puzzle_11_1();
    solve_the_puzzle_12_0();
    solve_the_puzzle_12_1();
    solve_the_puzzle_13_0();
    solve_the_puzzle_13_1();
    solve_the_puzzle_14_0();
    solve_the_puzzle_14_1().expect("error");
    solve_the_puzzle_15_0();
    solve_the_puzzle_15_1();
}
